#Hugo configuration
title = "ewrfdsgf"
baseURL = "https:\/\/swdfds.xcv.dsf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
